import {
  char,
  index,
  int,
  mysqlEnum,
  mysqlTable,
  uniqueIndex,
  varchar,
} from 'drizzle-orm/mysql-core';
import { createdAt, dt, id, ref, updatedAt } from './_columns.js';
import { MEMBERSHIP_KIND, MEMBERSHIP_STATUS, ONE_TIME_TOKEN_STATUS, USER_STATUS } from './enums.js';
import { tenants } from './tenancy.js';

/**
 * Authentication identity. There is deliberately no tenant/school column:
 * a user reaches a school only through a membership.
 */
export const users = mysqlTable(
  'users',
  {
    id: id(),
    email: varchar('email', { length: 254 }).notNull(),
    phone: varchar('phone', { length: 32 }),
    passwordHash: varchar('password_hash', { length: 255 }),
    firstName: varchar('first_name', { length: 100 }).notNull(),
    lastName: varchar('last_name', { length: 100 }).notNull().default(''),
    status: mysqlEnum('status', USER_STATUS).notNull().default('INVITED'),
    emailVerifiedAt: dt('email_verified_at'),
    lastLoginAt: dt('last_login_at'),
    passwordChangedAt: dt('password_changed_at'),
    failedLoginCount: int('failed_login_count').notNull().default(0),
    lockedUntil: dt('locked_until'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex('users_email_uq').on(t.email), index('users_status_idx').on(t.status)],
);

/**
 * Membership is the tenant boundary. `tenant_key` is the tenant id, or the
 * literal 'PLATFORM', so MySQL can enforce one membership per (user, tenant)
 * including the single platform membership (NULLs are not unique in MySQL).
 */
export const memberships = mysqlTable(
  'memberships',
  {
    id: id(),
    userId: ref('user_id')
      .notNull()
      .references(() => users.id),
    tenantId: ref('tenant_id').references(() => tenants.id),
    tenantKey: varchar('tenant_key', { length: 36 }).notNull(),
    kind: mysqlEnum('kind', MEMBERSHIP_KIND).notNull(),
    status: mysqlEnum('status', MEMBERSHIP_STATUS).notNull().default('INVITED'),
    joinedAt: dt('joined_at'),
    endedAt: dt('ended_at'),
    invitedBy: ref('invited_by'),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('memberships_user_tenant_uq').on(t.userId, t.tenantKey),
    /** Lets other tables reference a membership through a composite (tenant_id, id) foreign key. */
    uniqueIndex('memberships_tenant_id_uq').on(t.tenantId, t.id),
    index('memberships_tenant_status_idx').on(t.tenantId, t.status),
  ],
);

export const userSessions = mysqlTable(
  'user_sessions',
  {
    id: id(),
    userId: ref('user_id')
      .notNull()
      .references(() => users.id),
    membershipId: ref('membership_id').references(() => memberships.id),
    /** SHA-256 of the refresh token. The raw token is never stored. */
    refreshTokenHash: char('refresh_token_hash', { length: 64 }).notNull(),
    deviceName: varchar('device_name', { length: 100 }),
    deviceType: varchar('device_type', { length: 32 }),
    ipAddress: varchar('ip_address', { length: 45 }),
    userAgent: varchar('user_agent', { length: 500 }),
    expiresAt: dt('expires_at').notNull(),
    lastUsedAt: dt('last_used_at'),
    revokedAt: dt('revoked_at'),
    revokedReason: varchar('revoked_reason', { length: 64 }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('user_sessions_refresh_hash_uq').on(t.refreshTokenHash),
    index('user_sessions_user_idx').on(t.userId, t.revokedAt),
    index('user_sessions_membership_idx').on(t.membershipId),
  ],
);

/** The raw token is generated by the delivery worker, emailed, and never stored. */
export const passwordResetTokens = mysqlTable(
  'password_reset_tokens',
  {
    id: id(),
    userId: ref('user_id')
      .notNull()
      .references(() => users.id),
    tokenHash: char('token_hash', { length: 64 }),
    status: mysqlEnum('status', ONE_TIME_TOKEN_STATUS).notNull().default('PENDING'),
    expiresAt: dt('expires_at').notNull(),
    sentAt: dt('sent_at'),
    usedAt: dt('used_at'),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('password_reset_tokens_hash_uq').on(t.tokenHash),
    index('password_reset_tokens_user_idx').on(t.userId, t.status),
  ],
);

export const invitations = mysqlTable(
  'invitations',
  {
    id: id(),
    membershipId: ref('membership_id')
      .notNull()
      .references(() => memberships.id),
    tenantId: ref('tenant_id').references(() => tenants.id),
    email: varchar('email', { length: 254 }).notNull(),
    /** Name as typed by the inviter — shown until the invitee accepts, so an
     *  invitation never reveals details of an existing account. */
    invitedFirstName: varchar('invited_first_name', { length: 100 }),
    invitedLastName: varchar('invited_last_name', { length: 100 }),
    tokenHash: char('token_hash', { length: 64 }),
    status: mysqlEnum('status', ONE_TIME_TOKEN_STATUS).notNull().default('PENDING'),
    expiresAt: dt('expires_at').notNull(),
    sentAt: dt('sent_at'),
    acceptedAt: dt('accepted_at'),
    createdBy: ref('created_by'),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex('invitations_token_hash_uq').on(t.tokenHash),
    index('invitations_membership_idx').on(t.membershipId, t.status),
    index('invitations_tenant_idx').on(t.tenantId, t.status),
  ],
);
