import { expandPermissionPatterns } from './permissions.js';

/**
 * System roles. These are starting bundles of permissions, not hard-coded
 * behaviour: code never checks role codes. Schools cannot edit system roles,
 * but can create custom roles (e.g. a "Sub Admin" with selected permissions).
 */
export interface SystemRoleDef {
  code: string;
  name: string;
  description: string;
  scope: 'PLATFORM' | 'TENANT';
  /** Permission codes or patterns (`students.*`, `*`). */
  permissions: string[];
}

const TENANT_READ_ONLY = [
  'tenant.profile.read',
  'tenant.settings.read',
  'tenant.subscription.read',
  'members.read',
  'roles.read',
  'audit.read',
  'students.read',
  'students.admissions.read',
  'students.documents.read',
  'academics.read',
  'teachers.read',
  'attendance.read',
  'exams.read',
  'fees.read',
  'timetable.read',
  'leave.read',
  'communication.read',
  'library.read',
  'transport.read',
  'reports.read',
];

export const SYSTEM_ROLES: SystemRoleDef[] = [
  // ---- Platform roles --------------------------------------------------------
  {
    code: 'SUPER_ADMIN',
    name: 'Super Admin',
    description: 'Full platform access, including acting inside any school.',
    scope: 'PLATFORM',
    permissions: ['*'],
  },
  {
    code: 'PLATFORM_ADMIN',
    name: 'Platform Admin',
    description: 'Manages schools, provisioning and entitlements.',
    scope: 'PLATFORM',
    permissions: [
      'platform.tenants.*',
      'platform.subscriptions.read',
      'platform.entitlements.*',
      'platform.catalog.read',
      'platform.users.read',
      'platform.audit.read',
      ...TENANT_READ_ONLY,
    ],
  },
  {
    code: 'BILLING_ADMIN',
    name: 'Billing Admin',
    description: 'Manages subscriptions and plans.',
    scope: 'PLATFORM',
    permissions: [
      'platform.tenants.read',
      'platform.subscriptions.*',
      'platform.entitlements.read',
      'platform.catalog.read',
    ],
  },
  {
    code: 'SALES_ADMIN',
    name: 'Sales Admin',
    description: 'Onboards schools: reviews requests, views plans and subscriptions.',
    scope: 'PLATFORM',
    permissions: [
      'platform.tenants.read',
      'platform.tenants.review',
      'platform.tenants.create',
      'platform.subscriptions.read',
      'platform.catalog.read',
    ],
  },
  {
    code: 'OPERATIONS_ADMIN',
    name: 'Operations Admin',
    description: 'Runs schools day to day: provisioning, suspension, entitlements (read).',
    scope: 'PLATFORM',
    permissions: [
      'platform.tenants.read',
      'platform.tenants.update',
      'platform.tenants.provision',
      'platform.tenants.suspend',
      'platform.entitlements.read',
      'platform.catalog.read',
      'platform.audit.read',
    ],
  },
  {
    code: 'SUPPORT_ADMIN',
    name: 'Support Admin',
    description: 'Read-only support access to schools.',
    scope: 'PLATFORM',
    permissions: [
      'platform.tenants.read',
      'platform.tenants.access',
      'platform.entitlements.read',
      'platform.audit.read',
      ...TENANT_READ_ONLY,
    ],
  },

  // ---- School (tenant) system roles ----------------------------------------
  {
    code: 'SCHOOL_ADMIN',
    name: 'School Admin',
    description: 'Full access within the school, limited by the school’s plan.',
    scope: 'TENANT',
    permissions: expandPermissionPatterns(['*'], 'TENANT').filter((c) => c !== 'portal.access'),
  },
  {
    code: 'PRINCIPAL',
    name: 'Principal',
    description: 'Academic and administrative oversight.',
    scope: 'TENANT',
    permissions: [
      ...TENANT_READ_ONLY,
      'tenant.profile.update',
      'tenant.settings.update',
      'tenant.finance.read',
      'tenant.finance.manage',
      'tenant.finance.reveal',
      'academics.manage',
      'attendance.approve',
      'attendance.export',
      'attendance.statuses.manage',
      'attendance.settings.manage',
      'exams.manage',
      'exams.results.approve',
      'exams.results.publish',
      'fees.structures.publish',
      'fees.refunds.approve',
      'fees.waivers.approve',
      'fees.export',
      'fees.reconcile',
      'fees.arrears.manage',
      'fees.arrears.escalate',
      'timetable.manage',
      'timetable.publish',
      'timetable.export',
      'leave.approve',
      'communication.announcements.manage',
      'students.admissions.approve',
      'students.enroll',
      'students.settings.manage',
      'students.export',
      'students.import',
      'students.certificates.read',
      'students.certificates.issue',
      'students.certificates.void',
      'students.certificates.manage',
      'students.government_id.read',
      'teachers.assignments.manage',
      'teachers.documents.read',
      'teachers.reports.read',
      'teachers.attendance.read',
      'teachers.attendance.mark',
      'leave.types.manage',
      'teachers.export',
      'reports.export',
    ],
  },
  {
    code: 'ACCOUNTANT',
    name: 'Accountant',
    description: 'Fees, receipts and financial reports.',
    scope: 'TENANT',
    // Deliberately not `fees.*`: accountants request but never approve (separation of duties),
    // and cannot publish structures, approve refunds or approve waivers/write-offs.
    permissions: [
      'tenant.profile.read',
      'tenant.finance.read',
      'students.read',
      'academics.read',
      'fees.read',
      'fees.manage',
      'fees.settings.manage',
      'fees.payments.create',
      'fees.payments.verify',
      'fees.concessions.request',
      'fees.refunds.request',
      'fees.export',
      'fees.reconcile',
      'fees.arrears.manage',
      'reports.*',
      'communication.read',
    ],
  },
  {
    code: 'TEACHER',
    name: 'Teacher',
    description: 'Assigned classes: attendance, marks and timetable.',
    scope: 'TENANT',
    permissions: [
      'students.read',
      'teachers.read',
      'academics.read',
      'attendance.read',
      'attendance.mark',
      'attendance.correct',
      'exams.read',
      'exams.marks.enter',
      'timetable.read',
      'leave.read',
      'leave.request',
      'communication.read',
    ],
  },
  {
    code: 'RECEPTIONIST',
    name: 'Receptionist / Office Staff',
    description: 'Student records, admissions, documents and notices.',
    scope: 'TENANT',
    permissions: [
      'students.read',
      'students.create',
      'students.update',
      'students.enroll',
      'students.guardians.manage',
      'students.admissions.read',
      'students.admissions.manage',
      'students.documents.*',
      'academics.read',
      'attendance.read',
      'attendance.mark',
      'communication.read',
      'communication.announcements.manage',
    ],
  },
  {
    code: 'LIBRARIAN',
    name: 'Librarian',
    description: 'Library catalogue and circulation.',
    scope: 'TENANT',
    permissions: ['students.read', 'library.*', 'communication.read'],
  },
  {
    code: 'TRANSPORT_MANAGER',
    name: 'Transport Manager',
    description: 'Routes, vehicles and student transport.',
    scope: 'TENANT',
    permissions: ['students.read', 'transport.*', 'communication.read'],
  },
  {
    code: 'PARENT',
    name: 'Parent / Guardian',
    description: 'Portal access to linked students only.',
    scope: 'TENANT',
    permissions: ['portal.access'],
  },
];

export function resolveSystemRolePermissions(role: SystemRoleDef): string[] {
  // Platform roles may carry tenant permissions (used when acting inside a school).
  return expandPermissionPatterns(role.permissions);
}
