import { and, eq, inArray } from 'drizzle-orm';
import type { Deps } from '../../container.js';
import type { Executor } from '../../db/client.js';
import {
  invitations,
  memberships,
  roleAssignments,
  roles,
  users,
  type ScopeRef,
  type ScopeType,
} from '../../db/schema/index.js';
import { recordAudit } from '../../platform/audit.js';
import type { Actor } from '../../platform/context.js';
import { publishEvent } from '../../platform/outbox.js';
import { BusinessRuleError, ConflictError, NotFoundError } from '../../shared/errors.js';
import { addHours } from '../../shared/time.js';

export interface AssignmentInput {
  roleId: string;
  scopeType?: ScopeType;
  scopeRef?: ScopeRef | null;
}

export interface InviteInput {
  email: string;
  firstName: string;
  lastName?: string;
  /** null = platform membership */
  tenantId: string | null;
  assignments: AssignmentInput[];
}

/**
 * Find-or-create the user, create the membership (INVITED), assign roles and
 * queue the invitation email — all in the caller's transaction. The invitation
 * token is generated by the email worker and only its hash is stored.
 */
export async function inviteMember(deps: Deps, tx: Executor, input: InviteInput, actor: Actor) {
  const email = input.email.trim().toLowerCase();
  const tenantKey = input.tenantId ?? 'PLATFORM';

  const [existing] = await tx.select().from(users).where(eq(users.email, email));
  let userId: string;
  if (existing) {
    if (existing.status === 'DEACTIVATED')
      throw new BusinessRuleError('OPERATION_NOT_ALLOWED', 'This account has been deactivated');
    userId = existing.id;
  } else {
    const [row] = await tx
      .insert(users)
      .values({
        email,
        firstName: input.firstName,
        lastName: input.lastName ?? '',
        status: 'INVITED',
      })
      .$returningId();
    userId = row!.id;
  }

  const [prior] = await tx
    .select()
    .from(memberships)
    .where(and(eq(memberships.userId, userId), eq(memberships.tenantKey, tenantKey)));
  let membershipId: string;
  if (prior) {
    if (prior.status === 'ACTIVE' || prior.status === 'SUSPENDED') {
      throw new ConflictError('DUPLICATE_RESOURCE', 'This person is already a member', {
        membership_id: prior.id,
      });
    }
    if (prior.status === 'INVITED') {
      // Changing a pending invitee's roles goes through PUT /members/:id/roles (with its checks).
      throw new ConflictError(
        'DUPLICATE_RESOURCE',
        'This person already has a pending invitation. Resend it or change their roles instead.',
        { membership_id: prior.id },
      );
    }
    // Re-inviting a REVOKED member reuses the membership (history is in the audit log).
    membershipId = prior.id;
    await tx
      .update(memberships)
      .set({ status: 'INVITED', endedAt: null, invitedBy: actor.userId })
      .where(eq(memberships.id, prior.id));
    await tx
      .update(roleAssignments)
      .set({ status: 'REVOKED' })
      .where(and(eq(roleAssignments.membershipId, prior.id), eq(roleAssignments.status, 'ACTIVE')));
  } else {
    const [row] = await tx
      .insert(memberships)
      .values({
        userId,
        tenantId: input.tenantId,
        tenantKey,
        kind: input.tenantId ? 'TENANT' : 'PLATFORM',
        status: 'INVITED',
        invitedBy: actor.userId,
      })
      .$returningId();
    membershipId = row!.id;
  }

  await assignRoles(tx, {
    membershipId,
    tenantId: input.tenantId,
    assignments: input.assignments,
    actor,
  });
  const invitationId = await queueInvitation(
    deps,
    tx,
    {
      membershipId,
      tenantId: input.tenantId,
      email,
      firstName: input.firstName,
      lastName: input.lastName ?? null,
    },
    actor,
  );

  await recordAudit(tx, actor, {
    tenantId: input.tenantId,
    action: 'MEMBER_INVITED',
    entityType: 'membership',
    entityId: membershipId,
    after: { email, role_ids: input.assignments.map((a) => a.roleId) },
  });
  return { userId, membershipId, invitationId };
}

/** Revoke outstanding invitations for the membership and queue a fresh one. */
export async function queueInvitation(
  deps: Deps,
  tx: Executor,
  input: {
    membershipId: string;
    tenantId: string | null;
    email: string;
    firstName: string | null;
    lastName: string | null;
  },
  actor: Actor,
) {
  await tx
    .update(invitations)
    .set({ status: 'REVOKED' })
    .where(
      and(
        eq(invitations.membershipId, input.membershipId),
        inArray(invitations.status, ['PENDING', 'SENT']),
      ),
    );
  const [row] = await tx
    .insert(invitations)
    .values({
      membershipId: input.membershipId,
      tenantId: input.tenantId,
      email: input.email,
      invitedFirstName: input.firstName,
      invitedLastName: input.lastName,
      expiresAt: addHours(deps.clock.now(), deps.env.INVITATION_TTL_HOURS),
      createdBy: actor.userId,
    })
    .$returningId();
  await publishEvent(tx, actor, {
    tenantId: input.tenantId,
    eventType: 'invitation.created',
    aggregateType: 'invitation',
    aggregateId: row!.id,
    payload: { invitation_id: row!.id, membership_id: input.membershipId },
  });
  return row!.id;
}

/**
 * Validate and insert role assignments. A role must belong to the same tenant
 * (or be a system role of the matching scope) — cross-tenant references are
 * impossible by construction.
 */
export async function assignRoles(
  tx: Executor,
  input: {
    membershipId: string;
    tenantId: string | null;
    assignments: AssignmentInput[];
    actor: Actor;
  },
) {
  if (input.assignments.length === 0) return;
  const ids = [...new Set(input.assignments.map((a) => a.roleId))];
  const found = await tx.select().from(roles).where(inArray(roles.id, ids));
  const expectedScope = input.tenantId ? 'TENANT' : 'PLATFORM';
  for (const id of ids) {
    const role = found.find((r) => r.id === id);
    const visible =
      role &&
      role.status === 'ACTIVE' &&
      role.scope === expectedScope &&
      (role.tenantId === null || role.tenantId === input.tenantId);
    if (!visible) throw new NotFoundError('Role', { role_id: id });
  }
  await tx.insert(roleAssignments).values(
    input.assignments.map((a) => ({
      tenantId: input.tenantId,
      membershipId: input.membershipId,
      roleId: a.roleId,
      scopeType:
        a.scopeType ?? (input.tenantId ? ('ALL_TENANT' as const) : ('ALL_TENANTS' as const)),
      scopeRef: a.scopeRef ?? null,
      createdBy: input.actor.userId,
    })),
  );
}
